version: "3"

services:
    console:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/source
        # stdin_open: true
        # tty: true