FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src

# copy the .sln and .csproj files into /src/<folder> (minimally required to get dependencies)
COPY CourseRegistrationSystem.sln ./
COPY CourseRegistrationSystem/CourseRegistrationSystem.csproj CourseRegistrationSystem/
COPY CourseRegistrationSystem.Tests/CourseRegistrationSystem.Tests.csproj CourseRegistrationSystem.Tests/
# get all dependencies
RUN dotnet restore CourseRegistrationSystem.sln

# copy everything else into /src
COPY . ./
# create a debug build for the main project into /app/build
RUN dotnet build CourseRegistrationSystem -c Debug -o /app/build --no-restore

# CMD [ "dotnet", "CourseRegistrationSystem/obj/Debug/netcoreapp3.1/CourseRegistrationSystem.dll" ]
CMD [ "dotnet", "run", "-p", "CourseRegistrationSystem" ]